name: Deploy RBC Life Dev

on:
  push:
    branches: ["master"]

env:
  AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: "rbc-life-dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3.5.0
        with:
          node-version-file: .nvmrc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: yarn

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: idp-creator # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
